### ISSUE TITLE
Android: 'polling' -> 'websocket' transport upgrade and $upgradeTimeout issues.

### ISSUE THREAD

**Issue by AndrewSologor** [walkor/phpsocket.io#158] opened 2018-06-22 13:04 UTC
It happens only on Android in 50% connection cases. Tested on Android 6.0, Google Chrome v67.
Workerman v3.5.5, phpsocket.io v1.1.9. I have configuration with 1 worker.

In some cases during the transport upgrade server holds last polling request for 5 seconds and then upgrade timeout is being triggered, but client already established websocket connection 4.9 seconds ago.
So we have situation where client library works via websocket transport and server still works with polling and does not react on packages from the websocket connection.
Then client tries to send ping requests and after 60 seconds it tries to reconnect (and this connection issue may repeat again, or may not).

I've increased `PHPSocketIO\Engine\Engine::$upgradeTimeout` from 5 to 10 seconds and all works fine (except 5 seconds connection delay sometimes).

<details><summary>Request and my log details here</summary>
<p>

First AJAX request params:
```
EIO: 3
transport: polling
t: MGdN9Nj
```

Server response: `{"sid":"658c5f4339cbd641036fb2f8","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}`

Second AJAX request params:
```
EIO: 3
transport: polling
t: MGdN9Rs
sid: 658c5f4339cbd641036fb2f8
```

Now in parallel with this request WS connection is being established.
But last AJAX will return response in a 5 seconds and server calls `Socket::check()` many times during that time and then `Socket::upgradeTimeoutCallback()`.

### Logs from `phpsocket.io/src/Engine/Transports/Polling.php`:

When second AJAX passes fast:

```
Polling::onRequest()

Polling::onPollRequest()

Polling::send()

Polling::write()

Polling::pollRequestClean()

Polling::onRequest()

Polling::onPollRequest()

Polling::send()

Polling::write()

Polling::pollRequestClean()

Polling::doClose()
```

When second AJAX freezes for 5 seconds:

```
Polling::onRequest()

Polling::onPollRequest()

Polling::send()

Polling::write()

Polling::pollRequestClean()
```

### Logs from `phpsocket.io/src/Engine/Socket.php`:

When second AJAX passes fast:
```
Socket::write()

Socket::send()

Socket::sendPacket()

Socket::flush()

Socket::maybeUpgrade()

Socket::flush()

Socket::onDrainCallback()

Socket::onUpgradePacket()

Socket::flush()

Socket::onDrainCallback()

Socket::check()

Socket::onUpgradePacket()

Socket::upgradeCleanup()

Socket::clearTransport()

Socket::setTransport()

Socket::setupSendCallback()

Socket::setPingTimeout()

Socket::flush()
```

When second AJAX freezes for 5 seconds:
```
Socket::write()

Socket::send()

Socket::sendPacket()

Socket::flush()

Socket::flush()

Socket::onDrainCallback()

Socket::maybeUpgrade()

Socket::onUpgradePacket()

Socket::check()

Socket::check()

Socket::check()

Socket::check()

Socket::check()

Socket::check()

Socket::check()

Socket::check()

Socket::check()

Socket::upgradeTimeoutCallback()

Socket::upgradeCleanup()
```
</p>
</details>

**Comment by walkor** [comment] 2018-06-23 14:42
Thank you  for your post.
But I can't reproduce this issue.
I can't tell what is the problem.

**Comment by AndrewSologor** [comment] 2018-06-24 18:22
I'll try with fresh server later.

**Comment by AndrewSologor** [comment] 2018-06-25 14:05
I've reproduced the issue with fresh server configuration on my local machine (https://github.com/walkor/phpsocket.io#simple-chat from your readme).

Also I've reproduced source of the issue on your demo page (http://www.workerman.net/demos/phpsocketio-chat/) but seems your server accepts WS connection without timeout and I see responses on ping requests via established WS connection.
![phpsocket io](https://user-images.githubusercontent.com/18735654/41853924-a939e358-7897-11e8-954b-0a35ad08f14f.png)
It's a screenshot from the chrome remote debugger. Pay attention on second xhr request which in some cases takes 5.00-5.02 seconds but in other cases it takes less than 1 sec. On desktop browser it never takes so long.

**Comment by walkor** [comment] 2018-07-16 06:11
Closing since it seems we can't help here.

**Closed by walkor** 2018-07-16 06:11 UTC

**Comment by tihoho** [comment] 2018-08-18 20:29
Earlier (I do not know how now) javascript on androyd specially cut performance up to 10 seconds, and up to 15 with an inactive tab. For the sake of saving the resources of the phone. You did not think / read that the problem could be in the JS itself and not in the socket settings?
(excuse me for a bad english dialect)

**Comment by troublezzb** [comment] 2019-12-12 10:35
I hope it can help you.
echo 0 > /proc/sys/net/ipv4/tcp_tw_recycle
